apiVersion: v1  
kind: Service  
metadata:  
 name: traefik
 namespace: kube-public
spec:  
  selector:
    app: traefik-ingress-lb
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30021
    - name: dashboard
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30042