apiVersion: v1  
kind: Service  
metadata:  
 name: traefik
 namespace: kube-public
spec:  
  selector:
    app: traefik
  ports:
    - name: http
      protocol: TCP
      port: 30021
      targetPort: 80
      nodePort: 30021
    - name: admin
      protocol: TCP
      port: 30042
      targetPort: 8080
      nodePort: 30042